EMAIL = "cecomen.bg@gmail.com"
PASSWORD = "Skatefinger1"
DESCRIPTION = "Her leaks: https://t.me/HqLeeks\n#fyp #CapCut"
TIKTOK_LINK_TEMPLATE = "https://www.tiktok.com/@"
LOGIN_PAGE_LINK = "https://www.tiktok.com/login/phone-or-email/email"
USERNAME_INPUT = "username"
PASSWORD_INPUT = "input[type='password']"
LOGIN_BTN = "button[type='submit'"
VERIFY_LOGIN_TEXT = "login-modal-title"
VIDEO_INPUT_PATH = "//*[@id='root']/div/div/div[2]/div[2]/div/div/div/div[1]/div[2]/div/input"
DESCRIPTION_INPUT_FIELD = "//*[@id='root']/div/div/div[2]/div[2]/div/div/div/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div/div/div/div/div/div/span/span"
POST_BTN = "//*[@id='root']/div/div/div[2]/div[2]/div/div/div/div[4]/div/button[1]"